import { Roastery, Cafe, Review, Discussion, Reply } from '@/types'

export const roasteries: Roastery[] = [
  {
    id: "1",
    name: "Common Ground Roasters",
    location: "Singapore",
    description: "Specializing in single-origin beans from Southeast Asia with a focus on sustainable sourcing. We work directly with farmers to ensure fair trade practices and exceptional quality.",
    rating: 4.8,
    reviewCount: 124,
    specialties: ["Single Origin", "Sustainable", "Fair Trade"],
    website: "https://commonground.sg",
    phone: "+65 6789 0123",
    address: "32 Lorong 17 Geylang, Singapore 388482",
    images: ["/roasteries/common-ground-1.jpg", "/roasteries/common-ground-2.jpg"],
  },
  {
    id: "2",
    name: "Perc Coffee Roasters",
    location: "Singapore",
    description: "Award-winning roastery known for their meticulous light roasts and experimental processing methods. Our team of Q-graders ensures every batch meets our exacting standards.",
    rating: 4.7,
    reviewCount: 89,
    specialties: ["Light Roast", "Experimental Processing", "Q-Grader Certified"],
    website: "https://perccoffee.sg",
    phone: "+65 6234 5678",
    address: "20 Circular Road, Singapore 049447",
    images: ["/roasteries/perc-1.jpg", "/roasteries/perc-2.jpg"],
  },
  {
    id: "3",
    name: "Nylon Coffee Roasters",
    location: "Singapore",
    description: "Pioneering the specialty coffee scene in Singapore with their unique flavor profiles. We believe in transparency and traceability, showcasing the unique characteristics of each origin.",
    rating: 4.9,
    reviewCount: 156,
    specialties: ["Specialty", "Transparent Sourcing", "Unique Profiles"],
    website: "https://nyloncoffee.com.sg",
    phone: "+65 6345 6789",
    address: "438 Joo Chiat Road, Singapore 427656",
    images: ["/roasteries/nylon-1.jpg", "/roasteries/nylon-2.jpg"],
  },
  {
    id: "4",
    name: "Liberty Coffee",
    location: "Singapore",
    description: "Micro-roastery focusing on small-batch, high-quality coffees. We roast to order to ensure maximum freshness and flavor in every cup.",
    rating: 4.6,
    reviewCount: 67,
    specialties: ["Micro-batch", "Fresh Roast", "Small Batch"],
    website: "https://libertycoffee.sg",
    phone: "+65 6456 7890",
    address: "55 Ang Mo Kio Street 65, Singapore 569063",
    images: ["/roasteries/liberty-1.jpg", "/roasteries/liberty-2.jpg"],
  },
  {
    id: "5",
    name: "Spin Coffee Roasters",
    location: "Singapore",
    description: "Eco-conscious roastery committed to reducing our carbon footprint. We use solar-powered roasting equipment and compostable packaging.",
    rating: 4.5,
    reviewCount: 45,
    specialties: ["Eco-friendly", "Solar Powered", "Compostable Packaging"],
    website: "https://spincoffee.sg",
    phone: "+65 6567 8901",
    address: "1 Commonwealth Lane, Singapore 149543",
    images: ["/roasteries/spin-1.jpg", "/roasteries/spin-2.jpg"],
  },
  {
    id: "6",
    name: "Chye Seng Huat Hardware",
    location: "Singapore",
    description: "Coffee bar and roastery in a restored hardware shop. Known for their creative blends and innovative brewing methods.",
    rating: 4.7,
    reviewCount: 112,
    specialties: ["Creative Blends", "Innovative Brewing", "Heritage Location"],
    website: "https://cshhcoffee.com",
    phone: "+65 6678 9012",
    address: "150 Tyrwhitt Road, Singapore 207563",
    images: ["/roasteries/cshh-1.jpg", "/roasteries/cshh-2.jpg"],
  },
]

export const cafes: Cafe[] = [
  {
    id: "1",
    name: "Chin Mee Chin Confectionery",
    location: "Singapore",
    description: "Traditional kopitiam serving classic Singaporean coffee and toast. A heritage experience with authentic Nanyang coffee culture.",
    rating: 4.6,
    reviewCount: 234,
    specialties: ["Traditional", "Heritage", "Nanyang Coffee"],
    phone: "+65 6345 6789",
    address: "204 East Coast Road, Singapore 428908",
    hours: "7:30 AM - 5:00 PM (Tue-Sun)",
    images: ["/cafes/cmc-1.jpg", "/cafes/cmc-2.jpg"],
  },
  {
    id: "2",
    name: "Monday Off",
    location: "Singapore",
    description: "Cozy neighborhood cafe with excellent pour-over and espresso drinks. Perfect for a relaxed coffee break.",
    rating: 4.8,
    reviewCount: 178,
    specialties: ["Pour-over", "Espresso", "Cozy Atmosphere"],
    phone: "+65 6789 0123",
    address: "462 Crawford Lane, Singapore 190462",
    hours: "8:00 AM - 6:00 PM (Tue-Sun)",
    images: ["/cafes/monday-off-1.jpg", "/cafes/monday-off-2.jpg"],
  },
  {
    id: "3",
    name: "Sarnies",
    location: "Singapore",
    description: "Australian-style cafe with great coffee and brunch. Known for their friendly service and consistent quality.",
    rating: 4.5,
    reviewCount: 156,
    specialties: ["Australian Style", "Brunch", "Friendly Service"],
    phone: "+65 6234 5678",
    address: "136 Telok Ayer Street, Singapore 068603",
    hours: "7:30 AM - 4:00 PM (Mon-Fri), 8:30 AM - 4:00 PM (Sat-Sun)",
    images: ["/cafes/sarnies-1.jpg", "/cafes/sarnies-2.jpg"],
  },
  {
    id: "4",
    name: "The Coffee Academics",
    location: "Singapore",
    description: "Award-winning coffee chain with a focus on education and quality. Their baristas are trained to the highest standards.",
    rating: 4.4,
    reviewCount: 312,
    specialties: ["Award-winning", "Education", "Professional Baristas"],
    phone: "+65 6456 7890",
    address: "391 Orchard Road, #02-01 Ngee Ann City, Singapore 238872",
    hours: "8:00 AM - 10:00 PM (Daily)",
    images: ["/cafes/tca-1.jpg", "/cafes/tca-2.jpg"],
  },
  {
    id: "5",
    name: "Dutch Colony",
    location: "Singapore",
    description: "Specialty coffee roaster and cafe with a focus on single-origin beans. Their cupping sessions are popular among enthusiasts.",
    rating: 4.7,
    reviewCount: 89,
    specialties: ["Single Origin", "Cupping Sessions", "Specialty"],
    phone: "+65 6567 8901",
    address: "55 Tiong Bahru Road, Singapore 168755",
    hours: "8:00 AM - 6:00 PM (Tue-Sun)",
    images: ["/cafes/dutch-colony-1.jpg", "/cafes/dutch-colony-2.jpg"],
  },
  {
    id: "6",
    name: "Kith Cafe",
    location: "Singapore",
    description: "Modern cafe with multiple locations across Singapore. Known for their consistent quality and beautiful spaces.",
    rating: 4.3,
    reviewCount: 267,
    specialties: ["Modern", "Multiple Locations", "Consistent Quality"],
    phone: "+65 6678 9012",
    address: "1 Raffles Place, #03-59 One Raffles Place, Singapore 048616",
    hours: "7:00 AM - 10:00 PM (Mon-Fri), 8:00 AM - 9:00 PM (Sat-Sun)",
    images: ["/cafes/kith-1.jpg", "/cafes/kith-2.jpg"],
  },
]

export const reviews: Review[] = [
  {
    id: "1",
    userId: "user1",
    userName: "coffee_lover_sg",
    targetId: "1",
    targetType: "roastery",
    rating: 5,
    title: "Best single origin in Singapore!",
    content: "Common Ground never disappoints. Their Ethiopian Yirgacheffe is absolutely phenomenal - floral notes with a bright acidity. The staff is knowledgeable and always happy to share brewing tips.",
    createdAt: "2024-01-15T10:30:00Z",
    helpfulCount: 24,
  },
  {
    id: "2",
    userId: "user2",
    userName: "barista_joe",
    targetId: "2",
    targetType: "roastery",
    rating: 4,
    title: "Great light roasts, but pricey",
    content: "Perc's light roasts are exceptional and really bring out the unique characteristics of each bean. However, the prices are on the higher side. Worth it for special occasions.",
    createdAt: "2024-01-10T14:22:00Z",
    helpfulCount: 18,
  },
  {
    id: "3",
    userId: "user3",
    userName: "cafe_hopper",
    targetId: "1",
    targetType: "cafe",
    rating: 5,
    title: "Authentic heritage experience",
    content: "Chin Mee Chin is a must-visit for anyone wanting to experience traditional Singaporean coffee culture. The kaya toast is perfect and the kopi is authentic. Go early to avoid the queue!",
    createdAt: "2024-01-08T09:15:00Z",
    helpfulCount: 31,
  },
]

export const discussions: Discussion[] = [
  {
    id: "1",
    title: "Best pour-over ratio for Ethiopian beans?",
    content: "I've been experimenting with different ratios for my Ethiopian Yirgacheffe and would love to hear what works best for you all. Currently using 1:16 but finding it a bit weak. Thinking of trying 1:14 or 1:15. Any recommendations?",
    author: {
      id: "user1",
      name: "coffee_junkie",
    },
    category: "Brewing Methods",
    tags: ["pour-over", "ethiopian", "ratio", "v60"],
    createdAt: "2024-01-15T08:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
    replyCount: 23,
    viewCount: 156,
    likes: 12,
  },
  {
    id: "2",
    title: "V60 vs Kalita Wave - which do you prefer?",
    content: "Looking to upgrade my pour-over setup. Currently using a Hario V60 but curious about the Kalita Wave. I've heard the flat bottom gives more consistent extraction. Has anyone tried both? What are your thoughts?",
    author: {
      id: "user2",
      name: "brew_master",
    },
    category: "Equipment",
    tags: ["v60", "kalita", "pour-over", "equipment"],
    createdAt: "2024-01-14T12:00:00Z",
    updatedAt: "2024-01-15T09:00:00Z",
    replyCount: 45,
    viewCount: 289,
    likes: 28,
  },
  {
    id: "3",
    title: "New roastery alert: Check out [Roastery Name]",
    content: "Just discovered this amazing new roastery in my neighborhood. Their natural processed beans are incredible - lots of fruity notes without being too funky. Has anyone else tried their coffees?",
    author: {
      id: "user3",
      name: "bean_hunter",
    },
    category: "Roasteries",
    tags: ["new roastery", "natural process", "recommendation"],
    createdAt: "2024-01-13T16:30:00Z",
    updatedAt: "2024-01-14T11:00:00Z",
    replyCount: 12,
    viewCount: 98,
    likes: 8,
  },
  {
    id: "4",
    title: "Tips for dialing in a new espresso machine",
    content: "Just got my first espresso machine (a Breville Barista Express) and struggling to get consistent shots. Sometimes they're too sour, sometimes too bitter. Any tips for beginners on dialing in?",
    author: {
      id: "user4",
      name: "espresso_newbie",
    },
    category: "Espresso",
    tags: ["espresso", "beginner", "dialing in", "breville"],
    createdAt: "2024-01-12T10:00:00Z",
    updatedAt: "2024-01-13T15:00:00Z",
    replyCount: 34,
    viewCount: 234,
    likes: 19,
  },
  {
    id: "5",
    title: "Best cafes for working with laptop?",
    content: "Looking for cafes with good wifi, plenty of power outlets, and not too crowded during weekdays. Preferably in the CBD area. Any recommendations?",
    author: {
      id: "user5",
      name: "digital_nomad",
    },
    category: "Cafes",
    tags: ["work cafe", "wifi", "cbd", "laptop-friendly"],
    createdAt: "2024-01-11T14:00:00Z",
    updatedAt: "2024-01-12T09:00:00Z",
    replyCount: 28,
    viewCount: 187,
    likes: 15,
  },
]

export const replies: Reply[] = [
  {
    id: "1",
    discussionId: "1",
    author: {
      id: "user2",
      name: "brew_master",
    },
    content: "For Ethiopian beans, I typically go with 1:15.5 - it brings out the floral notes while maintaining good body. Try grinding slightly finer than you would for a 1:16 ratio.",
    createdAt: "2024-01-15T08:30:00Z",
    likes: 8,
  },
  {
    id: "2",
    discussionId: "1",
    author: {
      id: "user3",
      name: "barista_jane",
    },
    content: "I've found that water temperature makes a big difference with Ethiopians. Try 195°F instead of 205°F - it really helps highlight the delicate flavors.",
    createdAt: "2024-01-15T09:00:00Z",
    likes: 12,
  },
]
